export const countries = [
  {
    name: "Andorra",
    code: "AD",
    emoji: "🇦🇩",
    unicode: "U+1F1E6 U+1F1E9",
    image: require("../../assets/flag/ad.svg").default,
    dial_code: "+376",
    phoneLength: 6,
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    emoji: "🇦🇪",
    unicode: "U+1F1E6 U+1F1EA",
    image: require("../../assets/flag/ae.svg").default,
    dial_code: "+971",
    phoneLength: 9,
  },
  {
    name: "Afghanistan",
    code: "AF",
    emoji: "🇦🇫",
    unicode: "U+1F1E6 U+1F1EB",
    image: require("../../assets/flag/af.svg").default,
    dial_code: "+93",
    phoneLength: 9,
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    emoji: "🇦🇬",
    unicode: "U+1F1E6 U+1F1EC",
    image: require("../../assets/flag/ag.svg").default,
    dial_code: "+1268",
    phoneLength: 7,
  },
  {
    name: "Anguilla",
    code: "AI",
    emoji: "🇦🇮",
    unicode: "U+1F1E6 U+1F1EE",
    image: require("../../assets/flag/ai.svg").default,
    dial_code: "+1264",
    phoneLength: 7,
  },
  {
    name: "Albania",
    code: "AL",
    emoji: "🇦🇱",
    unicode: "U+1F1E6 U+1F1F1",
    image: require("../../assets/flag/al.svg").default,
    dial_code: "+355",
    phoneLength: 9,
  },
  {
    name: "Armenia",
    code: "AM",
    emoji: "🇦🇲",
    unicode: "U+1F1E6 U+1F1F2",
    image: require("../../assets/flag/am.svg").default,
    dial_code: "+374",
    phoneLength: 8,
  },
  {
    name: "Angola",
    code: "AO",
    emoji: "🇦🇴",
    unicode: "U+1F1E6 U+1F1F4",
    image: require("../../assets/flag/ao.svg").default,
    dial_code: "+244",
    phoneLength: 9,
  },
  {
    name: "Argentina",
    code: "AR",
    emoji: "🇦🇷",
    unicode: "U+1F1E6 U+1F1F7",
    image: require("../../assets/flag/ar.svg").default,
    dial_code: "+54",
    phoneLength: 10,
  },
  {
    name: "Austria",
    code: "AT",
    emoji: "🇦🇹",
    unicode: "U+1F1E6 U+1F1F9",
    image: require("../../assets/flag/at.svg").default,
    dial_code: "+43",
    phoneLength: 10,
  },
  {
    name: "Australia",
    code: "AU",
    emoji: "🇦🇺",
    unicode: "U+1F1E6 U+1F1FA",
    image: require("../../assets/flag/au.svg").default,
    dial_code: "+61",
    phoneLength: 9,
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    emoji: "🇦🇿",
    unicode: "U+1F1E6 U+1F1FF",
    image: require("../../assets/flag/az.svg").default,
    dial_code: "+994",
    phoneLength: 9,
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    emoji: "🇧🇦",
    unicode: "U+1F1E7 U+1F1E6",
    image: require("../../assets/flag/ba.svg").default,
    dial_code: "+387",
    phoneLength: 8,
  },
  {
    name: "Barbados",
    code: "BB",
    emoji: "🇧🇧",
    unicode: "U+1F1E7 U+1F1E7",
    image: require("../../assets/flag/bb.svg").default,
    dial_code: "+1246",
    phoneLength: 7,
  },
  {
    name: "Bangladesh",
    code: "BD",
    emoji: "🇧🇩",
    unicode: "U+1F1E7 U+1F1E9",
    image: require("../../assets/flag/bd.svg").default,
    dial_code: "+880",
    phoneLength: 10,
  },
  {
    name: "Belgium",
    code: "BE",
    emoji: "🇧🇪",
    unicode: "U+1F1E7 U+1F1EA",
    image: require("../../assets/flag/be.svg").default,
    dial_code: "+32",
    phoneLength: 9,
  },
  {
    name: "Bulgaria",
    code: "BG",
    emoji: "🇧🇬",
    unicode: "U+1F1E7 U+1F1EC",
    image: require("../../assets/flag/bg.svg").default,
    dial_code: "+359",
    phoneLength: 9,
  },
  {
    name: "Bahrain",
    code: "BH",
    emoji: "🇧🇭",
    unicode: "U+1F1E7 U+1F1ED",
    image: require("../../assets/flag/bh.svg").default,
    dial_code: "+973",
    phoneLength: 8,
  },
  {
    name: "Burundi",
    code: "BI",
    emoji: "🇧🇮",
    unicode: "U+1F1E7 U+1F1EE",
    image: require("../../assets/flag/bi.svg").default,
    dial_code: "+257",
    phoneLength: 8,
  },
  {
    name: "Benin",
    code: "BJ",
    emoji: "🇧🇯",
    unicode: "U+1F1E7 U+1F1EF",
    image: require("../../assets/flag/bj.svg").default,
    dial_code: "+229",
    phoneLength: 8,
  },
  {
    name: "Canada",
    code: "CA",
    emoji: "🇨🇦",
    unicode: "U+1F1E8 U+1F1E6",
    image: require("../../assets/flag/ca.svg").default,
    dial_code: "+1",
    phoneLength: 10,
  },
  {
    name: "Switzerland",
    code: "CH",
    emoji: "🇨🇭",
    unicode: "U+1F1E8 U+1F1ED",
    image: require("../../assets/flag/ch.svg").default,
    dial_code: "+41",
    phoneLength: 9,
  },
  {
    name: "China",
    code: "CN",
    emoji: "🇨🇳",
    unicode: "U+1F1E8 U+1F1F3",
    image: require("../../assets/flag/cn.svg").default,
    dial_code: "+86",
    phoneLength: 11,
  },
  {
    name: "Cyprus",
    code: "CY",
    emoji: "🇨🇾",
    unicode: "U+1F1E8 U+1F1FE",
    image: require("../../assets/flag/cy.svg").default,
    dial_code: "+357",
    phoneLength: 8,
  },
  {
    name: "Czech Republic",
    code: "CZ",
    emoji: "🇨🇿",
    unicode: "U+1F1E8 U+1F1FF",
    image: require("../../assets/flag/cz.svg").default,
    dial_code: "+420",
    phoneLength: 9,
  },
  {
    name: "Germany",
    code: "DE",
    emoji: "🇩🇪",
    unicode: "U+1F1E9 U+1F1EA",
    image: require("../../assets/flag/de.svg").default,
    dial_code: "+49",
    phoneLength: 11,
  },
  {
    name: "Djibouti",
    code: "DJ",
    emoji: "🇩🇯",
    unicode: "U+1F1E9 U+1F1EF",
    image: require("../../assets/flag/dj.svg").default,
    dial_code: "+253",
    phoneLength: 8,
  },
  {
    name: "Denmark",
    code: "DK",
    emoji: "🇩🇰",
    unicode: "U+1F1E9 U+1F1F0",
    image: require("../../assets/flag/dk.svg").default,
    dial_code: "+45",
    phoneLength: 8,
  },
  {
    name: "Dominica",
    code: "DM",
    emoji: "🇩🇲",
    unicode: "U+1F1E9 U+1F1F2",
    image: require("../../assets/flag/dm.svg").default,
    dial_code: "+1767",
    phoneLength: 7,
  },
  {
    name: "Dominican Republic",
    code: "DO",
    emoji: "🇩🇴",
    unicode: "U+1F1E9 U+1F1F4",
    image: require("../../assets/flag/do.svg").default,
    dial_code: "+1",
    phoneLength: 10,
  },
  {
    name: "Algeria",
    code: "DZ",
    emoji: "🇩🇿",
    unicode: "U+1F1E9 U+1F1FF",
    image: require("../../assets/flag/dz.svg").default,
    dial_code: "+213",
    phoneLength: 9,
  },
  {
    name: "Ecuador",
    code: "EC",
    emoji: "🇪🇨",
    unicode: "U+1F1EA U+1F1E8",
    image: require("../../assets/flag/ec.svg").default,
    dial_code: "+593",
    phoneLength: 9,
  },
  {
    name: "Estonia",
    code: "EE",
    emoji: "🇪🇪",
    unicode: "U+1F1EA U+1F1EA",
    image: require("../../assets/flag/ee.svg").default,
    dial_code: "+372",
    phoneLength: 8,
  },
  {
    name: "Egypt",
    code: "EG",
    emoji: "🇪🇬",
    unicode: "U+1F1EA U+1F1EC",
    image: require("../../assets/flag/eg.svg").default,
    dial_code: "+20",
    phoneLength: 10,
  },
  {
    name: "Western Sahara",
    code: "EH",
    emoji: "🇪🇭",
    unicode: "U+1F1EA U+1F1ED",
    image: require("../../assets/flag/eh.svg").default,
    dial_code: "+212",
    phoneLength: 9,
  },
  {
    name: "Spain",
    code: "ES",
    emoji: "🇪🇸",
    unicode: "U+1F1EA U+1F1F8",
    image: require("../../assets/flag/es.svg").default,
    dial_code: "+34",
    phoneLength: 9,
  },
  {
    name: "Ethiopia",
    code: "ET",
    emoji: "🇪🇹",
    unicode: "U+1F1EA U+1F1F9",
    image: require("../../assets/flag/et.svg").default,
    dial_code: "+251",
    phoneLength: 9,
  },
  {
    name: "Finland",
    code: "FI",
    emoji: "🇫🇮",
    unicode: "U+1F1EB U+1F1EE",
    image: require("../../assets/flag/fi.svg").default,
    dial_code: "+358",
    phoneLength: 9,
  },
  {
    name: "Fiji",
    code: "FJ",
    emoji: "🇫🇯",
    unicode: "U+1F1EB U+1F1EF",
    image: require("../../assets/flag/fj.svg").default,
    dial_code: "+679",
    phoneLength: 7,
  },
  {
    name: "France",
    code: "FR",
    emoji: "🇫🇷",
    unicode: "U+1F1EB U+1F1F7",
    image: require("../../assets/flag/fr.svg").default,
    dial_code: "+33",
    phoneLength: 9,
  },
  {
    name: "Gabon",
    code: "GA",
    emoji: "🇬🇦",
    unicode: "U+1F1EC U+1F1E6",
    image: require("../../assets/flag/ga.svg").default,
    dial_code: "+241",
    phoneLength: 8,
  },
  {
    name: "United Kingdom",
    code: "GB",
    emoji: "🇬🇧",
    unicode: "U+1F1EC U+1F1E7",
    image: require("../../assets/flag/gb.svg").default,
    dial_code: "+44",
    phoneLength: 10,
  },
  {
    name: "Georgia",
    code: "GE",
    emoji: "🇬🇪",
    unicode: "U+1F1EC U+1F1EA",
    image: require("../../assets/flag/ge.svg").default,
    dial_code: "+995",
    phoneLength: 9,
  },
  {
    name: "Ghana",
    code: "GH",
    emoji: "🇬🇭",
    unicode: "U+1F1EC U+1F1ED",
    image: require("../../assets/flag/gh.svg").default,
    dial_code: "+233",
    phoneLength: 9,
  },
  {
    name: "Gibraltar",
    code: "GI",
    emoji: "🇬🇮",
    unicode: "U+1F1EC U+1F1EE",
    image: require("../../assets/flag/gi.svg").default,
    dial_code: "+350",
    phoneLength: 8,
  },
  {
    name: "Gambia",
    code: "GM",
    emoji: "🇬🇲",
    unicode: "U+1F1EC U+1F1F2",
    image: require("../../assets/flag/gm.svg").default,
    dial_code: "+220",
    phoneLength: 7,
  },
  {
    name: "Guinea",
    code: "GN",
    emoji: "🇬🇳",
    unicode: "U+1F1EC U+1F1F3",
    image: require("../../assets/flag/gn.svg").default,
    dial_code: "+224",
    phoneLength: 9,
  },
  {
    name: "Greece",
    code: "GR",
    emoji: "🇬🇷",
    unicode: "U+1F1EC U+1F1F7",
    image: require("../../assets/flag/gr.svg").default,
    dial_code: "+30",
    phoneLength: 10,
  },
  {
    name: "Guatemala",
    code: "GT",
    emoji: "🇬🇹",
    unicode: "U+1F1EC U+1F1F9",
    image: require("../../assets/flag/gt.svg").default,
    dial_code: "+502",
    phoneLength: 8,
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    emoji: "🇬🇼",
    unicode: "U+1F1EC U+1F1FC",
    image: require("../../assets/flag/gw.svg").default,
    dial_code: "+245",
    phoneLength: 7,
  },
  {
    name: "Guyana",
    code: "GY",
    emoji: "🇬🇾",
    unicode: "U+1F1EC U+1F1FE",
    image: require("../../assets/flag/gy.svg").default,
    dial_code: "+592",
    phoneLength: 7,
  },
  {
    name: "Hong Kong",
    code: "HK",
    emoji: "🇭🇰",
    unicode: "U+1F1ED U+1F1F0",
    image: require("../../assets/flag/hk.svg").default,
    dial_code: "+852",
    phoneLength: 8,
  },
  {
    name: "Honduras",
    code: "HN",
    emoji: "🇭🇳",
    unicode: "U+1F1ED U+1F1F3",
    image: require("../../assets/flag/hn.svg").default,
    dial_code: "+504",
    phoneLength: 8,
  },
  {
    name: "Croatia",
    code: "HR",
    emoji: "🇭🇷",
    unicode: "U+1F1ED U+1F1F7",
    image: require("../../assets/flag/hr.svg").default,
    dial_code: "+385",
    phoneLength: 9,
  },
  {
    name: "Haiti",
    code: "HT",
    emoji: "🇭🇹",
    unicode: "U+1F1ED U+1F1F9",
    image: require("../../assets/flag/ht.svg").default,
    dial_code: "+509",
    phoneLength: 8,
  },
  {
    name: "Hungary",
    code: "HU",
    emoji: "🇭🇺",
    unicode: "U+1F1ED U+1F1FA",
    image: require("../../assets/flag/hu.svg").default,
    dial_code: "+36",
    phoneLength: 9,
  },
  {
    name: "Indonesia",
    code: "ID",
    emoji: "🇮🇩",
    unicode: "U+1F1EE U+1F1E9",
    image: require("../../assets/flag/id.svg").default,
    dial_code: "+62",
    phoneLength: 10,
  },
  {
    name: "Ireland",
    code: "IE",
    emoji: "🇮🇪",
    unicode: "U+1F1EE U+1F1EA",
    image: require("../../assets/flag/ie.svg").default,
    dial_code: "+353",
    phoneLength: 9,
  },
  {
    name: "Israel",
    code: "IL",
    emoji: "🇮🇱",
    unicode: "U+1F1EE U+1F1F1",
    image: require("../../assets/flag/il.svg").default,
    dial_code: "+972",
    phoneLength: 9,
  },
  {
    name: "India",
    code: "IN",
    emoji: "🇮🇳",
    unicode: "U+1F1EE U+1F1F3",
    image: require("../../assets/flag/in.svg").default,
    dial_code: "+91",
    phoneLength: 10,
  },
  {
    name: "Iraq",
    code: "IQ",
    emoji: "🇮🇶",
    unicode: "U+1F1EE U+1F1F6",
    image: require("../../assets/flag/iq.svg").default,
    dial_code: "+964",
    phoneLength: 10,
  },
  {
    name: "Iran",
    code: "IR",
    emoji: "🇮🇷",
    unicode: "U+1F1EE U+1F1F7",
    image: require("../../assets/flag/ir.svg").default,
    dial_code: "+98",
    phoneLength: 10,
  },
  {
    name: "Iceland",
    code: "IS",
    emoji: "🇮🇸",
    unicode: "U+1F1EE U+1F1F8",
    image: require("../../assets/flag/is.svg").default,
    dial_code: "+354",
    phoneLength: 7,
  },
  {
    name: "Italy",
    code: "IT",
    emoji: "🇮🇹",
    unicode: "U+1F1EE U+1F1F9",
    image: require("../../assets/flag/it.svg").default,
    dial_code: "+39",
    phoneLength: 9,
  },
  {
    name: "Jamaica",
    code: "JM",
    emoji: "🇯🇲",
    unicode: "U+1F1EF U+1F1F2",
    image: require("../../assets/flag/jm.svg").default,
    dial_code: "+1876",
    phoneLength: 7,
  },
  {
    name: "Jordan",
    code: "JO",
    emoji: "🇯🇴",
    unicode: "U+1F1EF U+1F1F4",
    image: require("../../assets/flag/jo.svg").default,
    dial_code: "+962",
    phoneLength: 9,
  },
  {
    name: "Japan",
    code: "JP",
    emoji: "🇯🇵",
    unicode: "U+1F1EF U+1F1F5",
    image: require("../../assets/flag/jp.svg").default,
    dial_code: "+81",
    phoneLength: 10,
  },
  {
    name: "Kenya",
    code: "KE",
    emoji: "🇰🇪",
    unicode: "U+1F1F0 U+1F1EA",
    image: require("../../assets/flag/ke.svg").default,
    dial_code: "+254",
    phoneLength: 9,
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    emoji: "🇰🇬",
    unicode: "U+1F1F0 U+1F1EC",
    image: require("../../assets/flag/kg.svg").default,
    dial_code: "+996",
    phoneLength: 9,
  },
  {
    name: "Cambodia",
    code: "KH",
    emoji: "🇰🇭",
    unicode: "U+1F1F0 U+1F1ED",
    image: require("../../assets/flag/kh.svg").default,
    dial_code: "+855",
    phoneLength: 9,
  },
  {
    name: "Kiribati",
    code: "KI",
    emoji: "🇰🇮",
    unicode: "U+1F1F0 U+1F1EE",
    image: require("../../assets/flag/ki.svg").default,
    dial_code: "+686",
    phoneLength: 5,
  },
  {
    name: "Comoros",
    code: "KM",
    emoji: "🇰🇲",
    unicode: "U+1F1F0 U+1F1F2",
    image: require("../../assets/flag/km.svg").default,
    dial_code: "+269",
    phoneLength: 7,
  },
  {
    name: "North Korea",
    code: "KP",
    emoji: "🇰🇵",
    unicode: "U+1F1F0 U+1F1F5",
    image: require("../../assets/flag/kp.svg").default,
    dial_code: "+850",
    phoneLength: 9,
  },
  {
    name: "South Korea",
    code: "KR",
    emoji: "🇰🇷",
    unicode: "U+1F1F0 U+1F1F7",
    image: require("../../assets/flag/kr.svg").default,
    dial_code: "+82",
    phoneLength: 10,
  },
  {
    name: "Kuwait",
    code: "KW",
    emoji: "🇰🇼",
    unicode: "U+1F1F0 U+1F1FC",
    image: require("../../assets/flag/kw.svg").default,
    dial_code: "+965",
    phoneLength: 8,
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    emoji: "🇰🇿",
    unicode: "U+1F1F0 U+1F1FF",
    image: require("../../assets/flag/kz.svg").default,
    dial_code: "+7",
    phoneLength: 10,
  },
  {
    name: "Laos",
    code: "LA",
    emoji: "🇱🇦",
    unicode: "U+1F1F1 U+1F1E6",
    image: require("../../assets/flag/la.svg").default,
    dial_code: "+856",
    phoneLength: 9,
  },
  {
    name: "Lebanon",
    code: "LB",
    emoji: "🇱🇧",
    unicode: "U+1F1F1 U+1F1E7",
    image: require("../../assets/flag/lb.svg").default,
    dial_code: "+961",
    phoneLength: 8,
  },
  {
    name: "Sri Lanka",
    code: "LK",
    emoji: "🇱🇰",
    unicode: "U+1F1F1 U+1F1F0",
    image: require("../../assets/flag/lk.svg").default,
    dial_code: "+94",
    phoneLength: 9,
  },
  {
    name: "Liberia",
    code: "LR",
    emoji: "🇱🇷",
    unicode: "U+1F1F1 U+1F1F7",
    image: require("../../assets/flag/lr.svg").default,
    dial_code: "+231",
    phoneLength: 8,
  },
  {
    name: "Lesotho",
    code: "LS",
    emoji: "🇱🇸",
    unicode: "U+1F1F1 U+1F1F8",
    image: require("../../assets/flag/ls.svg").default,
    dial_code: "+266",
    phoneLength: 8,
  },
  {
    name: "Lithuania",
    code: "LT",
    emoji: "🇱🇹",
    unicode: "U+1F1F1 U+1F1F9",
    image: require("../../assets/flag/lt.svg").default,
    dial_code: "+370",
    phoneLength: 8,
  },
  {
    name: "Luxembourg",
    code: "LU",
    emoji: "🇱🇺",
    unicode: "U+1F1F1 U+1F1FA",
    image: require("../../assets/flag/lu.svg").default,
    dial_code: "+352",
    phoneLength: 9,
  },
  {
    name: "Latvia",
    code: "LV",
    emoji: "🇱🇻",
    unicode: "U+1F1F1 U+1F1FB",
    image: require("../../assets/flag/lv.svg").default,
    dial_code: "+371",
    phoneLength: 8,
  },
  {
    name: "Libya",
    code: "LY",
    emoji: "🇱🇾",
    unicode: "U+1F1F1 U+1F1FE",
    image: require("../../assets/flag/ly.svg").default,
    dial_code: "+218",
    phoneLength: 9,
  },
  {
    name: "Morocco",
    code: "MA",
    emoji: "🇲🇦",
    unicode: "U+1F1F2 U+1F1E6",
    image: require("../../assets/flag/ma.svg").default,
    dial_code: "+212",
    phoneLength: 9,
  },
  {
    name: "Monaco",
    code: "MC",
    emoji: "🇲🇨",
    unicode: "U+1F1F2 U+1F1E8",
    image: require("../../assets/flag/mc.svg").default,
    dial_code: "+377",
    phoneLength: 8,
  },
  {
    name: "Moldova",
    code: "MD",
    emoji: "🇲🇩",
    unicode: "U+1F1F2 U+1F1E9",
    image: require("../../assets/flag/md.svg").default,
    dial_code: "+373",
    phoneLength: 8,
  },
  {
    name: "Montenegro",
    code: "ME",
    emoji: "🇲🇪",
    unicode: "U+1F1F2 U+1F1EA",
    image: require("../../assets/flag/me.svg").default,
    dial_code: "+382",
    phoneLength: 8,
  },
  {
    name: "Madagascar",
    code: "MG",
    emoji: "🇲🇬",
    unicode: "U+1F1F2 U+1F1EC",
    image: require("../../assets/flag/mg.svg").default,
    dial_code: "+261",
    phoneLength: 9,
  },
  {
    name: "Marshall Islands",
    code: "MH",
    emoji: "🇲🇭",
    unicode: "U+1F1F2 U+1F1ED",
    image: require("../../assets/flag/mh.svg").default,
    dial_code: "+692",
    phoneLength: 7,
  },
  {
    name: "Macedonia",
    code: "MK",
    emoji: "🇲🇰",
    unicode: "U+1F1F2 U+1F1F0",
    image: require("../../assets/flag/mk.svg").default,
    dial_code: "+389",
    phoneLength: 8,
  },
  {
    name: "Mali",
    code: "ML",
    emoji: "🇲🇱",
    unicode: "U+1F1F2 U+1F1F1",
    image: require("../../assets/flag/ml.svg").default,
    dial_code: "+223",
    phoneLength: 8,
  },
  {
    name: "Myanmar",
    code: "MM",
    emoji: "🇲🇲",
    unicode: "U+1F1F2 U+1F1F2",
    image: require("../../assets/flag/mm.svg").default,
    dial_code: "+95",
    phoneLength: 9,
  },
  {
    name: "Mongolia",
    code: "MN",
    emoji: "🇲🇳",
    unicode: "U+1F1F2 U+1F1F3",
    image: require("../../assets/flag/mn.svg").default,
    dial_code: "+976",
    phoneLength: 8,
  },
  {
    name: "Mauritania",
    code: "MR",
    emoji: "🇲🇷",
    unicode: "U+1F1F2 U+1F1F7",
    image: require("../../assets/flag/mr.svg").default,
    dial_code: "+222",
    phoneLength: 8,
  },
  {
    name: "Malta",
    code: "MT",
    emoji: "🇲🇹",
    unicode: "U+1F1F2 U+1F1F9",
    image: require("../../assets/flag/mt.svg").default,
    dial_code: "+356",
    phoneLength: 8,
  },
  {
    name: "Mauritius",
    code: "MU",
    emoji: "🇲🇺",
    unicode: "U+1F1F2 U+1F1FA",
    image: require("../../assets/flag/mu.svg").default,
    dial_code: "+230",
    phoneLength: 8,
  },
  {
    name: "Maldives",
    code: "MV",
    emoji: "🇲🇻",
    unicode: "U+1F1F2 U+1F1FB",
    image: require("../../assets/flag/mv.svg").default,
    dial_code: "+960",
    phoneLength: 7,
  },
  {
    name: "Malawi",
    code: "MW",
    emoji: "🇲🇼",
    unicode: "U+1F1F2 U+1F1FC",
    image: require("../../assets/flag/mw.svg").default,
    dial_code: "+265",
    phoneLength: 9,
  },
  {
    name: "Mexico",
    code: "MX",
    emoji: "🇲🇽",
    unicode: "U+1F1F2 U+1F1FD",
    image: require("../../assets/flag/mx.svg").default,
    dial_code: "+52",
    phoneLength: 10,
  },
  {
    name: "Malaysia",
    code: "MY",
    emoji: "🇲🇾",
    unicode: "U+1F1F2 U+1F1FE",
    image: require("../../assets/flag/my.svg").default,
    dial_code: "+60",
    phoneLength: 9,
  },
  {
    name: "Mozambique",
    code: "MZ",
    emoji: "🇲🇿",
    unicode: "U+1F1F2 U+1F1FF",
    image: require("../../assets/flag/mz.svg").default,
    dial_code: "+258",
    phoneLength: 9,
  },
  {
    name: "Namibia",
    code: "NA",
    emoji: "🇳🇦",
    unicode: "U+1F1F3 U+1F1E6",
    image: require("../../assets/flag/na.svg").default,
    dial_code: "+264",
    phoneLength: 9,
  },
  {
    name: "New Caledonia",
    code: "NC",
    emoji: "🇳🇨",
    unicode: "U+1F1F3 U+1F1E8",
    image: require("../../assets/flag/nc.svg").default,
    dial_code: "+687",
    phoneLength: 6,
  },
  {
    name: "Niger",
    code: "NE",
    emoji: "🇳🇪",
    unicode: "U+1F1F3 U+1F1EA",
    image: require("../../assets/flag/ne.svg").default,
    dial_code: "+227",
    phoneLength: 8,
  },
  {
    name: "Nigeria",
    code: "NG",
    emoji: "🇳🇬",
    unicode: "U+1F1F3 U+1F1EC",
    image: require("../../assets/flag/ng.svg").default,
    dial_code: "+234",
    phoneLength: 10,
  },
  {
    name: "Nicaragua",
    code: "NI",
    emoji: "🇳🇮",
    unicode: "U+1F1F3 U+1F1EE",
    image: require("../../assets/flag/ni.svg").default,
    dial_code: "+505",
    phoneLength: 8,
  },
  {
    name: "Netherlands",
    code: "NL",
    emoji: "🇳🇱",
    unicode: "U+1F1F3 U+1F1F1",
    image: require("../../assets/flag/nl.svg").default,
    dial_code: "+31",
    phoneLength: 9,
  },
  {
    name: "Norway",
    code: "NO",
    emoji: "🇳🇴",
    unicode: "U+1F1F3 U+1F1F4",
    image: require("../../assets/flag/no.svg").default,
    dial_code: "+47",
    phoneLength: 8,
  },
  {
    name: "Nepal",
    code: "NP",
    emoji: "🇳🇵",
    unicode: "U+1F1F3 U+1F1F5",
    image: require("../../assets/flag/np.svg").default,
    dial_code: "+977",
    phoneLength: 10,
  },
  {
    name: "Nauru",
    code: "NR",
    emoji: "🇳🇷",
    unicode: "U+1F1F3 U+1F1F7",
    image: require("../../assets/flag/nr.svg").default,
    dial_code: "+674",
    phoneLength: 7,
  },
  {
    name: "New Zealand",
    code: "NZ",
    emoji: "🇳🇿",
    unicode: "U+1F1F3 U+1F1FF",
    image: require("../../assets/flag/nz.svg").default,
    dial_code: "+64",
    phoneLength: 9,
  },
  {
    name: "Oman",
    code: "OM",
    emoji: "🇴🇲",
    unicode: "U+1F1F4 U+1F1F2",
    image: require("../../assets/flag/om.svg").default,
    dial_code: "+968",
    phoneLength: 8,
  },
  {
    name: "Panama",
    code: "PA",
    emoji: "🇵🇦",
    unicode: "U+1F1F5 U+1F1E6",
    image: require("../../assets/flag/pa.svg").default,
    dial_code: "+507",
    phoneLength: 8,
  },
  {
    name: "Peru",
    code: "PE",
    emoji: "🇵🇪",
    unicode: "U+1F1F5 U+1F1EA",
    image: require("../../assets/flag/pe.svg").default,
    dial_code: "+51",
    phoneLength: 9,
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    emoji: "🇵🇬",
    unicode: "U+1F1F5 U+1F1EC",
    image: require("../../assets/flag/pg.svg").default,
    dial_code: "+675",
    phoneLength: 8,
  },
  {
    name: "Philippines",
    code: "PH",
    emoji: "🇵🇭",
    unicode: "U+1F1F5 U+1F1ED",
    image: require("../../assets/flag/ph.svg").default,
    dial_code: "+63",
    phoneLength: 10,
  },
  {
    name: "Pakistan",
    code: "PK",
    emoji: "🇵🇰",
    unicode: "U+1F1F5 U+1F1F0",
    image: require("../../assets/flag/pk.svg").default,
    dial_code: "+92",
    phoneLength: 10,
  },
  {
    name: "Poland",
    code: "PL",
    emoji: "🇵🇱",
    unicode: "U+1F1F5 U+1F1F1",
    image: require("../../assets/flag/pl.svg").default,
    dial_code: "+48",
    phoneLength: 9,
  },
  {
    name: "Puerto Rico",
    code: "PR",
    emoji: "🇵🇷",
    unicode: "U+1F1F5 U+1F1F7",
    image: require("../../assets/flag/pr.svg").default,
    dial_code: "+1787",
    phoneLength: 10,
  },
  {
    name: "Palestine",
    code: "PS",
    emoji: "🇵🇸",
    unicode: "U+1F1F5 U+1F1F8",
    image: require("../../assets/flag/ps.svg").default,
    dial_code: "+970",
    phoneLength: 9,
  },
  {
    name: "Portugal",
    code: "PT",
    emoji: "🇵🇹",
    unicode: "U+1F1F5 U+1F1F9",
    image: require("../../assets/flag/pt.svg").default,
    dial_code: "+351",
    phoneLength: 9,
  },
  {
    name: "Palau",
    code: "PW",
    emoji: "🇵🇼",
    unicode: "U+1F1F5 U+1F1FC",
    image: require("../../assets/flag/pw.svg").default,
    dial_code: "+680",
    phoneLength: 7,
  },
  {
    name: "Paraguay",
    code: "PY",
    emoji: "🇵🇾",
    unicode: "U+1F1F5 U+1F1FE",
    image: require("../../assets/flag/py.svg").default,
    dial_code: "+595",
    phoneLength: 9,
  },
  {
    name: "Qatar",
    code: "QA",
    emoji: "🇶🇦",
    unicode: "U+1F1F6 U+1F1E6",
    image: require("../../assets/flag/qa.svg").default,
    dial_code: "+974",
    phoneLength: 8,
  },
  {
    name: "Romania",
    code: "RO",
    emoji: "🇷🇴",
    unicode: "U+1F1F7 U+1F1F4",
    image: require("../../assets/flag/ro.svg").default,
    dial_code: "+40",
    phoneLength: 9,
  },
  {
    name: "Serbia",
    code: "RS",
    emoji: "🇷🇸",
    unicode: "U+1F1F7 U+1F1F8",
    image: require("../../assets/flag/rs.svg").default,
    dial_code: "+381",
    phoneLength: 9,
  },
  {
    name: "Russia",
    code: "RU",
    emoji: "🇷🇺",
    unicode: "U+1F1F7 U+1F1FA",
    image: require("../../assets/flag/ru.svg").default,
    dial_code: "+7",
    phoneLength: 10,
  },
  {
    name: "Rwanda",
    code: "RW",
    emoji: "🇷🇼",
    unicode: "U+1F1F7 U+1F1FC",
    image: require("../../assets/flag/rw.svg").default,
    dial_code: "+250",
    phoneLength: 9,
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    emoji: "🇸🇦",
    unicode: "U+1F1F8 U+1F1E6",
    image: require("../../assets/flag/sa.svg").default,
    dial_code: "+966",
    phoneLength: 9,
  },
  {
    name: "Solomon Islands",
    code: "SB",
    emoji: "🇸🇧",
    unicode: "U+1F1F8 U+1F1E7",
    image: require("../../assets/flag/sb.svg").default,
    dial_code: "+677",
    phoneLength: 7,
  },
  {
    name: "Seychelles",
    code: "SC",
    emoji: "🇸🇨",
    unicode: "U+1F1F8 U+1F1E8",
    image: require("../../assets/flag/sc.svg").default,
    dial_code: "+248",
    phoneLength: 7,
  },
  {
    name: "Sudan",
    code: "SD",
    emoji: "🇸🇩",
    unicode: "U+1F1F8 U+1F1E9",
    image: require("../../assets/flag/sd.svg").default,
    dial_code: "+249",
    phoneLength: 9,
  },
  {
    name: "Sweden",
    code: "SE",
    emoji: "🇸🇪",
    unicode: "U+1F1F8 U+1F1EA",
    image: require("../../assets/flag/se.svg").default,
    dial_code: "+46",
    phoneLength: 9,
  },
  {
    name: "Singapore",
    code: "SG",
    emoji: "🇸🇬",
    unicode: "U+1F1F8 U+1F1EC",
    image: require("../../assets/flag/sg.svg").default,
    dial_code: "+65",
    phoneLength: 8,
  },
  {
    name: "Slovenia",
    code: "SI",
    emoji: "🇸🇮",
    unicode: "U+1F1F8 U+1F1EE",
    image: require("../../assets/flag/si.svg").default,
    dial_code: "+386",
    phoneLength: 8,
  },
  {
    name: "Slovakia",
    code: "SK",
    emoji: "🇸🇰",
    unicode: "U+1F1F8 U+1F1F0",
    image: require("../../assets/flag/sk.svg").default,
    dial_code: "+421",
    phoneLength: 9,
  },
  {
    name: "Sierra Leone",
    code: "SL",
    emoji: "🇸🇱",
    unicode: "U+1F1F8 U+1F1F1",
    image: require("../../assets/flag/sl.svg").default,
    dial_code: "+232",
    phoneLength: 8,
  },
  {
    name: "San Marino",
    code: "SM",
    emoji: "🇸🇲",
    unicode: "U+1F1F8 U+1F1F2",
    image: require("../../assets/flag/sm.svg").default,
    dial_code: "+378",
    phoneLength: 10,
  },
  {
    name: "Senegal",
    code: "SN",
    emoji: "🇸🇳",
    unicode: "U+1F1F8 U+1F1F3",
    image: require("../../assets/flag/sn.svg").default,
    dial_code: "+221",
    phoneLength: 9,
  },
  {
    name: "Somalia",
    code: "SO",
    emoji: "🇸🇴",
    unicode: "U+1F1F8 U+1F1F4",
    image: require("../../assets/flag/so.svg").default,
    dial_code: "+252",
    phoneLength: 9,
  },
  {
    name: "Suriname",
    code: "SR",
    emoji: "🇸🇷",
    unicode: "U+1F1F8 U+1F1F7",
    image: require("../../assets/flag/sr.svg").default,
    dial_code: "+597",
    phoneLength: 7,
  },
  {
    name: "South Sudan",
    code: "SS",
    emoji: "🇸🇸",
    unicode: "U+1F1F8 U+1F1F8",
    image: require("../../assets/flag/ss.svg").default,
    dial_code: "+211",
    phoneLength: 9,
  },
  {
    name: "São Tomé and Príncipe",
    code: "ST",
    emoji: "🇸🇹",
    unicode: "U+1F1F8 U+1F1F9",
    image: require("../../assets/flag/st.svg").default,
    dial_code: "+239",
    phoneLength: 7,
  },
  {
    name: "El Salvador",
    code: "SV",
    emoji: "🇸🇻",
    unicode: "U+1F1F8 U+1F1FB",
    image: require("../../assets/flag/sv.svg").default,
    dial_code: "+503",
    phoneLength: 8,
  },
  {
    name: "Syria",
    code: "SY",
    emoji: "🇸🇾",
    unicode: "U+1F1F8 U+1F1FE",
    image: require("../../assets/flag/sy.svg").default,
    dial_code: "+963",
    phoneLength: 9,
  },
  {
    name: "Swaziland",
    code: "SZ",
    emoji: "🇸🇿",
    unicode: "U+1F1F8 U+1F1FF",
    image: require("../../assets/flag/sz.svg").default,
    dial_code: "+268",
    phoneLength: 8,
  },
  {
    name: "Chad",
    code: "TD",
    emoji: "🇹🇩",
    unicode: "U+1F1F9 U+1F1E9",
    image: require("../../assets/flag/td.svg").default,
    dial_code: "+235",
    phoneLength: 8,
  },
  {
    name: "Togo",
    code: "TG",
    emoji: "🇹🇬",
    unicode: "U+1F1F9 U+1F1EC",
    image: require("../../assets/flag/tg.svg").default,
    dial_code: "+228",
    phoneLength: 8,
  },
  {
    name: "Thailand",
    code: "TH",
    emoji: "🇹🇭",
    unicode: "U+1F1F9 U+1F1ED",
    image: require("../../assets/flag/th.svg").default,
    dial_code: "+66",
    phoneLength: 9,
  },
  {
    name: "Tajikistan",
    code: "TJ",
    emoji: "🇹🇯",
    unicode: "U+1F1F9 U+1F1EF",
    image: require("../../assets/flag/tj.svg").default,
    dial_code: "+992",
    phoneLength: 9,
  },
  {
    name: "Turkmenistan",
    code: "TM",
    emoji: "🇹🇲",
    unicode: "U+1F1F9 U+1F1F2",
    image: require("../../assets/flag/tm.svg").default,
    dial_code: "+993",
    phoneLength: 8,
  },
  {
    name: "Tunisia",
    code: "TN",
    emoji: "🇹🇳",
    unicode: "U+1F1F9 U+1F1F3",
    image: require("../../assets/flag/tn.svg").default,
    dial_code: "+216",
    phoneLength: 8,
  },
  {
    name: "Tonga",
    code: "TO",
    emoji: "🇹🇴",
    unicode: "U+1F1F9 U+1F1F4",
    image: require("../../assets/flag/to.svg").default,
    dial_code: "+676",
    phoneLength: 5,
  },
  {
    name: "Turkey",
    code: "TR",
    emoji: "🇹🇷",
    unicode: "U+1F1F9 U+1F1F7",
    image: require("../../assets/flag/tr.svg").default,
    dial_code: "+90",
    phoneLength: 10,
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    emoji: "🇹🇹",
    unicode: "U+1F1F9 U+1F1F9",
    image: require("../../assets/flag/tt.svg").default,
    dial_code: "+1868",
    phoneLength: 7,
  },
  {
    name: "Taiwan",
    code: "TW",
    emoji: "🇹🇼",
    unicode: "U+1F1F9 U+1F1FC",
    image: require("../../assets/flag/tw.svg").default,
    dial_code: "+886",
    phoneLength: 9,
  },
  {
    name: "Tanzania",
    code: "TZ",
    emoji: "🇹🇿",
    unicode: "U+1F1F9 U+1F1FF",
    image: require("../../assets/flag/tz.svg").default,
    dial_code: "+255",
    phoneLength: 9,
  },
  {
    name: "Ukraine",
    code: "UA",
    emoji: "🇺🇦",
    unicode: "U+1F1FA U+1F1E6",
    image: require("../../assets/flag/ua.svg").default,
    dial_code: "+380",
    phoneLength: 9,
  },
  {
    name: "Uganda",
    code: "UG",
    emoji: "🇺🇬",
    unicode: "U+1F1FA U+1F1EC",
    image: require("../../assets/flag/ug.svg").default,
    dial_code: "+256",
    phoneLength: 9,
  },
  {
    name: "United States",
    code: "US",
    emoji: "🇺🇸",
    unicode: "U+1F1FA U+1F1F8",
    image: require("../../assets/flag/us.svg").default,
    dial_code: "+1",
    phoneLength: 10,
  },
  {
    name: "Uruguay",
    code: "UY",
    emoji: "🇺🇾",
    unicode: "U+1F1FA U+1F1FE",
    image: require("../../assets/flag/uy.svg").default,
    dial_code: "+598",
    phoneLength: 8,
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    emoji: "🇺🇿",
    unicode: "U+1F1FA U+1F1FF",
    image: require("../../assets/flag/uz.svg").default,
    dial_code: "+998",
    phoneLength: 9,
  },
  {
    name: "Vatican City",
    code: "VA",
    emoji: "🇻🇦",
    unicode: "U+1F1FB U+1F1E6",
    image: require("../../assets/flag/va.svg").default,
    dial_code: "+379",
    phoneLength: 9,
  },
  {
    name: "Venezuela",
    code: "VE",
    emoji: "🇻🇪",
    unicode: "U+1F1FB U+1F1EA",
    image: require("../../assets/flag/ve.svg").default,
    dial_code: "+58",
    phoneLength: 10,
  },
  {
    name: "Vietnam",
    code: "VN",
    emoji: "🇻🇳",
    unicode: "U+1F1FB U+1F1F3",
    image: require("../../assets/flag/vn.svg").default,
    dial_code: "+84",
    phoneLength: 9,
  },
  {
    name: "Vanuatu",
    code: "VU",
    emoji: "🇻🇺",
    unicode: "U+1F1FB U+1F1FA",
    image: require("../../assets/flag/vu.svg").default,
    dial_code: "+678",
    phoneLength: 7,
  },
  {
    name: "Samoa",
    code: "WS",
    emoji: "🇼🇸",
    unicode: "U+1F1FC U+1F1F8",
    image: require("../../assets/flag/ws.svg").default,
    dial_code: "+685",
    phoneLength: 7,
  },
  {
    name: "Yemen",
    code: "YE",
    emoji: "🇾🇪",
    unicode: "U+1F1FE U+1F1EA",
    image: require("../../assets/flag/ye.svg").default,
    dial_code: "+967",
    phoneLength: 9,
  },
  {
    name: "South Africa",
    code: "ZA",
    emoji: "🇿🇦",
    unicode: "U+1F1FF U+1F1E6",
    image: require("../../assets/flag/za.svg").default,
    dial_code: "+27",
    phoneLength: 9,
  },
  {
    name: "Zambia",
    code: "ZM",
    emoji: "🇿🇲",
    unicode: "U+1F1FF U+1F1F2",
    image: require("../../assets/flag/zm.svg").default,
    dial_code: "+260",
    phoneLength: 9,
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    emoji: "🇿🇼",
    unicode: "U+1F1FF U+1F1FC",
    image: require("../../assets/flag/zw.svg").default,
    dial_code: "+263",
    phoneLength: 9,
  },
];
